import type { ClubEvent, Fest } from "./data";

export const catalogFests: Fest[] = [
  {
    id: "science",
    name: "Science & Innovation Fest 2027",
    eyebrow: "ASK. EXPERIMENT. DISCOVER.",
    description:
      "Explore the universe, build cleaner energy, and share an invention that makes everyday life better.",
    date: "19–20 FEB 2027",
    venue: "DRMC Science Courtyard",
    color: "blue",
  },
  {
    id: "creative",
    name: "Creative Media Fest 2027",
    eyebrow: "MAKE YOUR IDEAS VISIBLE",
    description:
      "Tell campus stories through photography, motion and print. Two days of making, sharing and learning together.",
    date: "12–13 MAR 2027",
    venue: "DRMC Arts & Media Studio",
    color: "pink",
  },
];

export const catalogEvents: ClubEvent[] = [
  {
    id: "web-workshop",
    festId: "winter",
    title: "Build Your First Website",
    category: "Workshop",
    description:
      "Build and publish a simple personal website with guided HTML, CSS and accessibility exercises. Bring your own laptop; starter files and mentor support are provided. Individual participation, with no prior web experience required.",
    start: "2026-12-19T14:00:00+06:00",
    end: "2026-12-19T16:30:00+06:00",
    deadline: "2026-12-16T23:59:00+06:00",
    venue: "Innovation Lab · Room 202",
    capacity: 45,
    fee: 0,
    icon: "code",
    level: "Beginner friendly",
  },
  {
    id: "fresh-code",
    festId: "freshers",
    title: "Freshers’ Coding Challenge",
    category: "Programming",
    description:
      "Try five approachable programming puzzles covering loops, conditions and simple problem solving. Python and C++ are supported. A practice round and mentor-led explanations help first-time contestants get comfortable.",
    start: "2027-01-15T14:00:00+06:00",
    end: "2027-01-15T16:00:00+06:00",
    deadline: "2027-01-13T23:59:00+06:00",
    venue: "Computer Lab · Block B",
    capacity: 60,
    fee: 0,
    icon: "terminal",
    level: "Beginner friendly",
  },
  {
    id: "space-quest",
    festId: "science",
    title: "Space Explorer Challenge",
    category: "Science",
    description:
      "Put your astronomy knowledge to work through a constellation puzzle, a planet-identification round and a space-mission quiz. Compete individually using the provided materials; no specialist equipment is needed.",
    start: "2027-02-19T09:30:00+06:00",
    end: "2027-02-19T11:30:00+06:00",
    deadline: "2027-02-17T23:59:00+06:00",
    venue: "Science Gallery · Hall 1",
    capacity: 55,
    fee: 0,
    icon: "spark",
    level: "All levels",
  },
  {
    id: "green-energy",
    festId: "science",
    title: "Green Energy Lab",
    category: "Workshop",
    description:
      "Experiment with miniature solar panels and wind turbines, measure their output, and power a model campus. Low-voltage kits and safety guidance are supplied. Each participant builds and tests a small renewable-energy prototype.",
    start: "2027-02-19T13:00:00+06:00",
    end: "2027-02-19T15:30:00+06:00",
    deadline: "2027-02-17T23:59:00+06:00",
    venue: "Science Lab · Room 3",
    capacity: 32,
    fee: 0,
    icon: "spark",
    level: "Beginner friendly",
  },
  {
    id: "innovation-showcase",
    festId: "science",
    title: "Innovation Showcase",
    category: "Science",
    description:
      "Demonstrate a student-made invention that solves an everyday problem. Bring a working model or interactive prototype and deliver a three-minute explanation of the problem, design choices and results. Individual entries only; disclose any AI assistance.",
    start: "2027-02-20T10:00:00+06:00",
    end: "2027-02-20T13:00:00+06:00",
    deadline: "2027-02-17T23:59:00+06:00",
    venue: "Science Courtyard · Exhibit Zone",
    capacity: 35,
    fee: 0,
    icon: "bot",
    level: "All levels",
  },
  {
    id: "photo-story",
    festId: "creative",
    title: "Campus Photo Story",
    category: "Photography",
    description:
      "Tell a campus story in five original photographs. Bring a phone or camera, follow the announced theme and seek consent before photographing people. The session includes a photo walk, selection time and a short presentation of your sequence.",
    start: "2027-03-12T09:00:00+06:00",
    end: "2027-03-12T12:00:00+06:00",
    deadline: "2027-03-10T23:59:00+06:00",
    venue: "Campus Courtyard · Meet at Gate 2",
    capacity: 50,
    fee: 0,
    icon: "pen",
    level: "All levels",
  },
  {
    id: "motion-lab",
    festId: "creative",
    title: "Motion Design Lab",
    category: "Design",
    description:
      "Learn keyframes, easing and visual storytelling while making a short looping animation. Bring a laptop with a browser; the workshop uses a free web-based editor and supplied practice assets. Beginners work through a guided bouncing-ball exercise.",
    start: "2027-03-12T14:00:00+06:00",
    end: "2027-03-12T16:30:00+06:00",
    deadline: "2027-03-10T23:59:00+06:00",
    venue: "Media Studio · Animation Room",
    capacity: 36,
    fee: 0,
    icon: "pen",
    level: "Beginner friendly",
  },
  {
    id: "poster-jam",
    festId: "creative",
    title: "Poster Jam",
    category: "Design",
    description:
      "Create a bold poster for a student-led campus initiative using collage, typography and a clear visual hierarchy. Paper, cutting tools and basic art materials are provided, or bring your laptop to work digitally. Submit one original design and a short explanation.",
    start: "2027-03-13T10:00:00+06:00",
    end: "2027-03-13T13:00:00+06:00",
    deadline: "2027-03-10T23:59:00+06:00",
    venue: "Arts Studio · Print Room",
    capacity: 40,
    fee: 0,
    icon: "pen",
    level: "All levels",
  },
];
