import type { Blog } from "./community-types";
const articles = [
  [
    "first-fest",
    "Your first tech fest: a calmer way to begin",
    "Campus life",
    "A little preparation leaves more room for discovery.",
    "campus",
    "Start with one event that makes you curious. Read its description, check the venue and note what you need to bring. A workshop is a good place to ask questions; a challenge is a chance to practise under a little pressure.\n\nUse the event directory to compare dates and deadlines. Once you register, save your campus pass and open My schedule to check for overlaps. Leave time between sessions for finding the next room and meeting people.\n\nBefore you arrive, charge your device and download any files the organizer requests. If your plans change, cancel your registration so another student can use the seat. The best first fest is one where you learn something and feel comfortable returning.",
  ],
  [
    "web-checklist",
    "Five checks before you publish a website",
    "Development",
    "Make your next project easier to use, test and explain.",
    "ai-web",
    "Start by testing the main task from beginning to end. Can someone understand what the site does, complete the form and find the result? A beautiful screen is only the beginning of a useful product.\n\nNext, try a narrow phone screen and a wider desktop screen. Check labels, contrast, keyboard navigation and loading messages. Images should fit their containers without pushing important buttons out of view.\n\nFinally, test missing fields, duplicate submissions and a lost connection. Keep secrets off the client and explain which features are demonstrations. Write a short README with setup steps and limitations. These checks help you present a project with confidence.",
  ],
  [
    "coding-practice",
    "Build a coding practice habit that lasts",
    "Programming",
    "Small, regular sessions beat an overwhelming problem list.",
    "code-sprint",
    "Choose a small problem and explain the input and expected output in your own words. Before coding, write one simple example and one edge case. This turns an intimidating question into a concrete task.\n\nSet aside a focused practice session. If you get stuck, inspect your assumptions before changing random lines. After solving the problem, test empty input where allowed, boundary values and repeated values.\n\nKeep a short notebook of mistakes and the idea that fixed them. In a timed challenge, read all the problems before deciding where to start. A steady approach makes practice useful even on days when you solve only one problem.",
  ],
  [
    "robot-test",
    "Give your robot a proper test day",
    "Robotics",
    "A repeatable test tells you more than one lucky run.",
    "robotics",
    "A robot that works once may still need tuning. Set up a small, repeatable test track and record the conditions: lighting, surface, battery level and sensor position. Change one variable at a time.\n\nStart slowly. Check whether sensors distinguish the line reliably, then adjust speed and steering. Keep wires secure and ask a mentor to review power connections before running new hardware. Follow the event's battery and safety requirements.\n\nLog each run, including failures. If your robot loses the line at the same corner, that is useful information. Reliable preparation is a better goal than chasing maximum speed in the first test.",
  ],
  [
    "design-access",
    "Design for the person using your screen",
    "Design",
    "Good interface decisions start with a clear task.",
    "design",
    "Ask what someone is trying to achieve on the page. Put the next useful action near the information needed to choose it. Clear labels often help more than decorative effects.\n\nCheck the design without relying on colour alone. A full event needs a written status as well as a different colour. Form errors should name the problem and explain how to fix it. Use real button elements and visible keyboard focus.\n\nTry the page with larger text and on a small screen. If the meaning survives those changes, your layout is becoming more flexible. Accessibility is part of making a product understandable from the start.",
  ],
  [
    "hackathon-scope",
    "Choose a hackathon idea you can finish",
    "Hackathons",
    "A small working flow is easier to demonstrate clearly.",
    "hack",
    "Write down one problem, one kind of user and one action your project should improve. If the idea needs five separate systems to make sense, reduce its scope before building.\n\nSketch the complete user journey and build the shortest version first. Use sample data that is clearly labelled. Keep notes on libraries, AI assistance and design decisions so your explanation is accurate.\n\nLeave time to test the final demonstration on a different screen. Prepare a fallback if the network fails, and be honest about unfinished work. A focused project with a clear result gives judges and classmates something concrete to discuss.",
  ],
  [
    "ai-responsibly",
    "Use AI as a learning partner",
    "AI workshop",
    "Ask better questions, inspect the answer and keep ownership of your work.",
    "first-ai",
    "Start with a specific task and enough context for the tool to understand it. Ask for an explanation, examples and assumptions rather than accepting the first answer without review.\n\nWhen AI produces code, run it and inspect what it does. Check sources before repeating factual claims. Avoid uploading private information or someone else's work without permission.\n\nKeep a record of how you used AI in a project. Explain what you changed and what you verified yourself. Responsible use means you can still describe your work, recognise its limitations and learn from the process.",
  ],
  [
    "space-curiosity",
    "Turn a space question into an investigation",
    "Science",
    "Observation, comparison and careful notes are a good starting point.",
    "space-quest",
    "Pick a question you can explore with observations or reliable reference material. For example, how does the visible night sky change through the evening? Write down what you expect before collecting information.\n\nRecord the date, time and conditions of an observation. Compare observations taken in similar conditions rather than assuming every difference has the same cause. Use trusted astronomy resources to check names and explanations.\n\nPresent the question, method and limitations alongside your result. You do not need an expensive instrument to practise scientific thinking; you need a question, a careful method and a willingness to revise your explanation.",
  ],
  [
    "photo-story",
    "Tell a campus story in five photographs",
    "Photography",
    "Make each frame contribute something different.",
    "photo-story",
    "Begin with a simple theme: a place preparing for an event, a maker at work or a quiet corner of campus. Plan a wide view, a detail and a moment that connects the two.\n\nAsk permission before photographing identifiable people and respect areas where photography is restricted. Look for clear light and a background that supports the subject. A phone camera is enough to practise composition.\n\nChoose a sequence, not just your five favourite images. Add short captions that describe what is actually shown. Editing should support the story without presenting staged or altered scenes as documentary facts.",
  ],
  [
    "event-day",
    "Your event-day checklist",
    "Community",
    "Keep your pass, schedule and essentials within reach.",
    "creative-fest",
    "Check the latest announcement before leaving. Organizers may update a room or add a practical reminder. Your event details and registration status are available from your account.\n\nSave your pass, note the start time and bring the materials named in the event description. Arrive with enough time to find the check-in area. A QR pass identifies your registration; entry still follows the organizer's rules.\n\nIf something looks wrong, use the helpline once a real contact number is published. After the event, take a moment to write down what you learned and one thing to try next. Campus events are a starting point for future projects and friendships.",
  ],
];
export const sampleBlogs: Blog[] = articles.map(
  ([id, title, category, excerpt, image, body], i) => ({
    id,
    title,
    category,
    excerpt,
    body,
    cover: `/images/clubos/${image}-960.webp`,
    author: "ClubOS editorial",
    published: true,
    createdAt: Date.parse("2026-09-21T06:00:00Z") + i * 86400000,
    updatedAt: Date.parse("2026-09-21T06:00:00Z") + i * 86400000,
  }),
);
